# Before Build
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - dotnet --info
  - ps: .\build.ps1 --target=AppVeyor

# Tests
test: off

# Branches to build
branches:
  only:
    - develop
    - master
    - main
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - tools -> build.cake

# Environment configuration
image: Visual Studio 2019

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/
